/**
 * Agent group ids generated by `randomUUID()` often start with a hex digit,
 * but OneCLI's `/api/agents` requires identifiers to start with a letter
 * (1-50 chars, lowercase + digits + hyphens). The forward helper prefixes
 * any non-letter-leading id; ids already matching `/^[a-z]/` (UUIDs starting
 * with a-f, `ag-...` legacy, etc.) pass through unchanged.
 *
 * Reverse only strips the prefix when the suffix would itself fail the
 * forward rule — that way a legitimate `g-<letter>...` id round-trips
 * intact instead of being mis-stripped to its tail.
 */
const ONECLI_PREFIX = 'g-';

export function toOneCliIdentifier(agentGroupId: string): string {
  return /^[a-z]/.test(agentGroupId) ? agentGroupId : `${ONECLI_PREFIX}${agentGroupId}`;
}

export function fromOneCliIdentifier(identifier: string): string {
  if (identifier.startsWith(ONECLI_PREFIX)) {
    const rest = identifier.slice(ONECLI_PREFIX.length);
    if (!/^[a-z]/.test(rest)) return rest;
  }
  return identifier;
}
